namespace: macos
name: softwareupdate
version: 1.0.1
readme: README.md
authors:
  - kostakoff
description: A collection of MacOS SoftwareUpdate community modules for Ansible
license_file: LICENSE
tags:
  - macos
  - softwareupdate
repository: https://github.com/kostakoff/macos.softwareupdate
documentation: https://github.com/kostakoff/macos.softwareupdate/wiki
homepage: https://github.com/kostakoff/macos.softwareupdate
issues: https://github.com/kostakoff/macos.softwareupdate/issues
build_ignore:
  - .gitignore
